inherit_from: .rubocop_todo.yml

require: rubocop-rails
AllCops:
  Exclude:
    - 'db/**/*'  
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/bundle/**/*'


Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
